name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        fetch-depth: 0
        fetch-tags: 'true'

    - name: Setup Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: '3.13'

    - name: Install required-version defined in pyproject.toml
      uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
      with:
        python-version: '3.13'
        enable-cache: 'true'

    - name: Build package
      run: uv build

    - name: Upload distribution
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: kalyke-apns
        path: dist/

  publish:
    runs-on: ubuntu-26.04
    environment:
      name: PyPI
      url: https://pypi.org/project/kalyke-apns/

    needs:
    - build

    permissions:
      contents: write
      id-token: write

    steps:
    - name: Retrieve release distributions
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: kalyke-apns
        path: dist/

    - name: Publish release distributions to PyPI
      uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2

    - name: Get the tag name
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> "${GITHUB_ENV}"

    - name: Create release
      uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
      with:
        name: v${{ env.TAG_NAME }}
        generate_release_notes: true
