name: Renovate

on:
  pull_request:
    paths:
      - .github/workflows/renovate.yml
      - renovate.json

jobs:
  renovate-json-validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@ee9f69e1f683ed0d08225086482b34fc9abe9300  # v2.1.0
